name: Create image and Deploy

on:
  push:
    branches:
      - 'master'
jobs:
  build_and_push_to_registry:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}   
      - name: Build and push shell
        uses: docker/build-push-action@v2
        with:
          context: ./shell-docker
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/acdh-oeaw/shell:latest
      - name: Build and push perl
        uses: docker/build-push-action@v2
        with:
          context: ./perl-docker
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/acdh-oeaw/perl:latest
      - name: Build and push perlsimple
        uses: docker/build-push-action@v2
        with:
          context: ./perlsimple-docker
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/acdh-oeaw/perlsimple:latest
      - name: Build and push java8
        uses: docker/build-push-action@v2
        with:
          context: ./java8-docker
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/acdh-oeaw/java8:latest

